feat: add filter pipe
Letto228/Angular-learnjs-150424 pull request #80
Opened 2024-05-18 20:50 UTC by fyece

2024-05-25 11:23 UTC, Letto228 requested changes
Нихао
Спасибо за терпение с ожиданием ревью!)

В целом, получилось не плохо, моледец!
Однако, запутано и с большим кол-во приведением типов. Давай попробуем для начала разобраться с типизацией, а потом попробуем логику привести в порядок и упростить. Понимаю, что было желание учесть все кейсы, но из-за этого немного погрязли в проверках( Для того, что разгрестись, я бы рекомендовал вынести все условия в говорящие константы, после этого все должно стать прозрачней и появится простор для оптимизаций условий

2024-05-25 11:23 UTC, Letto228 commented on src/app/shared/filter-by-property/filter-by-property.pipe.ts
> +        if (!values && Array.isArray(values)) {
А такое вообще возможно? 🤔

2024-05-25 11:23 UTC, Letto228 commented on src/app/shared/filter-by-property/filter-by-property.pipe.ts
> +        if (typeof values?.[0] !== 'object') {
Почему в таком случае возвращается null?

2024-05-25 11:23 UTC, Letto228 commented on src/app/shared/filter-by-property/filter-by-property.pipe.ts
> +        if (!values && Array.isArray(values)) {
Неплохо было бы в самом начале добавить отдельную проверку на `values`, в таком случае сузилась бы типизация и не пришлось бы ниже использовать `?.`)

2024-05-25 11:23 UTC, Letto228 commented on src/app/shared/filter-by-property/filter-by-property.pipe.ts
> +        if (values?.length === 0) {
А такое не подойдет `values?.length`? Нужно ли проверять явно на равенство 0?

2024-05-25 11:23 UTC, Letto228 commented on src/app/shared/filter-by-property/filter-by-property.pipe.ts
> +            return null;
И почему тут null возвращаем?)

2024-05-25 11:23 UTC, Letto228 commented on src/app/shared/filter-by-property/filter-by-property.pipe.ts
> +        if (!(propertyName in values[0])) {
Очень часто используется `values[0]` может в говорящую константу его вынести?

2024-05-25 11:23 UTC, Letto228 commented on src/app/shared/filter-by-property/filter-by-property.pipe.ts
> +            typeof values[0][propertyName as keyof (typeof values)[0]]
Ух, жестко, кажется тут и кроется недоработка типизации, давай попробуем сделать читаемей и менее запутанно) Хотя бы через вынос типов и констант

2024-05-25 11:23 UTC, Letto228 commented on src/app/shared/filter-by-property/filter-by-property.pipe.ts
> +            typeof values[0][propertyName as keyof (typeof values)[0]]
И почему тут null?))

Не совсем мне понятен принцип генерации возвращаемого значения 🤔

2024-05-25 11:23 UTC, Letto228 commented on src/app/shared/filter-by-property/filter-by-property.pipe.ts
> +                if (value !== null && typeof value === 'object') {
Уже же была проверка на пренадлежность value к объекту 🤔 Да и не сходится, выше идет проверка
`values?.[0] === 'string'`, а тут ниже `value === 'object'` при итерации по массиву. Видится, что это взаимоисключающие проверки и корректно работать такое не будет

2024-05-25 15:29 UTC, fyece commented on src/app/shared/filter-by-property/filter-by-property.pipe.ts
> +    ): T[] | null {
По ts знаний не так много, и такая запись использования К как ключа объекта видел когда то, но сам не использовал (а сейчас просто не вспомнил). Поэтому пытался сделать эти проверки в теле функции. Твоя запись выглядит намного лучше, поправил у себя

2024-05-25 15:29 UTC, fyece commented on src/app/shared/filter-by-property/filter-by-property.pipe.ts
> +        if (!values && Array.isArray(values)) {
Действительно, глупая запись, поправил

2024-05-25 15:30 UTC, fyece commented on src/app/shared/filter-by-property/filter-by-property.pipe.ts
> +        if (typeof values?.[0] !== 'object') {
Изначально думал возвращать null, если с параметрами фильтра что то не так (например несоответсвие типов у свойства и параметра поиска) . В подобных случаях стоит позвращать исходное значение (values)?

2024-05-25 15:33 UTC, fyece commented on src/app/shared/filter-by-property/filter-by-property.pipe.ts
> +        if (values?.length === 0) {
Обычно я так и делаю, даже не знаю почему тут так написал

2024-05-25 15:33 UTC, fyece commented on src/app/shared/filter-by-property/filter-by-property.pipe.ts
> +            return null;
По той же логике, думал, что при некорректных данных стоит возвращать null

2024-05-25 15:33 UTC, fyece commented on src/app/shared/filter-by-property/filter-by-property.pipe.ts
> +        if (!(propertyName in values[0])) {
Сейчас наперед понял что эту проверку уже заменит строгая типизация аргументов

2024-05-25 15:35 UTC, fyece commented on src/app/shared/filter-by-property/filter-by-property.pipe.ts
> +            typeof values[0][propertyName as keyof (typeof values)[0]]
Действительно выглядит запутано, попробовал сделать как смог, типизация агрументов у transform сильно упростила запись.
Надеюсь про null уже объяснил )

2024-05-25 15:36 UTC, fyece commented on src/app/shared/filter-by-property/filter-by-property.pipe.ts
> +                if (value !== null && typeof value === 'object') {
Увидел, многие проверки потёр, так как правильная типизация аргументов `transform` избавила от них. Так же понял почему не нужны проверки на !=null у value, так как у них не будет такого ключа при null

2024-05-25 15:39 UTC, fyece reviewed
Поправил новым коммитом

2024-05-26 15:32 UTC, Letto228 commented on src/app/shared/filter-by-property/filter-by-property.pipe.ts
> +                const searchValueLowerCase = (searchPropertyValue as string).toLowerCase();
Не плохо было бы вынести за пределы итераций по массиву данное определение. Еще рекомендация: `if (typeof searchPropertyValue === 'string')` является тайпгардом по этому приведение в данной строке к string - лишнее

2024-05-26 15:32 UTC, Letto228 commented on src/app/shared/filter-by-property/filter-by-property.pipe.ts
> +        if (typeof values?.[0] !== 'object') {
Да, я считаю, что так работало бы корректней)

2024-05-26 15:37 UTC, Letto228 approved these changes
Отлично! - аппрув

Оставил пару рекомендательных комментариев, посмотри пожалуйста. Они не критичны, по этому закрою ПР. Но если вопросы появятся - обязательно пиши!)

2024-05-26 15:37 UTC, closed without merging